services:

  api:
    image: ghcr.io/hitechtn/don-bosco-connect/backend:latest

  worker:
    image: ghcr.io/hitechtn/don-bosco-connect/backend:latest

  beat:
    image: ghcr.io/hitechtn/don-bosco-connect/backend:latest

  flower:
    image: ghcr.io/hitechtn/don-bosco-connect/backend:latest

  frontend:
    image: ghcr.io/hitechtn/don-bosco-connect/frontend:latest

  nginx:
    image: ghcr.io/hitechtn/don-bosco-connect/nginx:latest
