from app.models.academic import (
    AcademicYear,
    Class,
    ClassEnrollment,
    SchoolEvent,
    StudentParentLink,
    Subject,
    TeacherSubjectAssignment,
    TimetableSlot,
)
from app.models.ai import AIConversation, AIMessage
from app.models.course import Course, CourseFile, DocumentChunk
from app.models.enums import (
    AbsenceType,
    DifficultyLevel,
    EvaluationType,
    FileType,
    JustificationStatus,
    MessageRole,
    NotificationType,
    ProcessingStatus,
    ScheduleDay,
    UserRole,
    UserStatus,
)
from app.models.evaluation import (
    Absence,
    Evaluation,
    Grade,
    Quiz,
    QuizAttempt,
    QuizQuestion,
)
from app.models.gamification import Badge, StudentBadge, StudentProfile, XPTransaction
from app.models.messaging import Message, MessageThread, Notification, ThreadParticipant
from app.models.user import AuditLog, RefreshToken, User

__all__ = [
    "UserRole",
    "UserStatus",
    "ScheduleDay",
    "FileType",
    "ProcessingStatus",
    "EvaluationType",
    "DifficultyLevel",
    "MessageRole",
    "AbsenceType",
    "JustificationStatus",
    "NotificationType",
    "User",
    "RefreshToken",
    "AuditLog",
    "AcademicYear",
    "Class",
    "ClassEnrollment",
    "StudentParentLink",
    "Subject",
    "TeacherSubjectAssignment",
    "TimetableSlot",
    "SchoolEvent",
    "Course",
    "CourseFile",
    "DocumentChunk",
    "Evaluation",
    "Grade",
    "Quiz",
    "QuizQuestion",
    "QuizAttempt",
    "Absence",
    "AIConversation",
    "AIMessage",
    "MessageThread",
    "ThreadParticipant",
    "Message",
    "Notification",
    "StudentProfile",
    "Badge",
    "StudentBadge",
    "XPTransaction",
]
