"""revert grades to NUMERIC for exact decimal precision

Revision ID: 42a0cbf69db6
Revises: ea22d27c40c6
Create Date: 2026-06-06 22:51:17.068978

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "42a0cbf69db6"
down_revision: str | None = "ea22d27c40c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evaluations",
        "max_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
        existing_server_default=sa.text("20.0"),
    )
    op.alter_column(
        "evaluations",
        "coefficient",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=3, scale=1),
        existing_nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    op.alter_column(
        "grades",
        "score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "quiz_attempts",
        "score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "quiz_attempts",
        "max_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "subjects",
        "coefficient",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=3, scale=1),
        existing_nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subjects",
        "coefficient",
        existing_type=sa.Numeric(precision=3, scale=1),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    op.alter_column(
        "quiz_attempts",
        "max_score",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "quiz_attempts",
        "score",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "grades",
        "score",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "evaluations",
        "coefficient",
        existing_type=sa.Numeric(precision=3, scale=1),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    op.alter_column(
        "evaluations",
        "max_score",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        existing_server_default=sa.text("20.0"),
    )
    # ### end Alembic commands ###
