"""revert grades to NUMERIC for exact decimal precision

Revision ID: 9e79d9136ce7
Revises: 44c6e4431407
Create Date: 2026-06-06 23:02:28.682976

"""

from collections.abc import Sequence

revision: str = "9e79d9136ce7"
down_revision: str | None = "44c6e4431407"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
