# ruff: noqa: E501
"""sync models with current schema

Revision ID: ea22d27c40c6
Revises: 0003
Create Date: 2026-06-06 22:18:37.215013

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'ea22d27c40c6'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_absences_date', table_name='absences')
    op.drop_index('idx_absences_student', table_name='absences')
    op.alter_column('ai_conversations', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ai_messages', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ai_messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', 'system', name='message_role'),
               nullable=True)
    op.alter_column('ai_messages', 'confidence_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ai_messages', 'feedback',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('idx_ai_messages_conversation', table_name='ai_messages')
    op.drop_constraint('uq_announcement_user_emoji', 'announcement_reactions', type_='unique')
    op.alter_column('announcements', 'priority',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint('announcements_slug_key', 'announcements', type_='unique')
    op.drop_index('idx_ann_pinned', table_name='announcements')
    op.drop_index('idx_ann_publish_at', table_name='announcements')
    op.drop_index('idx_ann_slug', table_name='announcements')
    op.drop_index('idx_ann_status_visibility', table_name='announcements')
    op.create_index(op.f('ix_announcements_slug'), 'announcements', ['slug'], unique=True)
    op.alter_column('audit_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('class_enrollments', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('class_enrollments', 'class_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('class_enrollments_student_id_class_id_academic_year_id_key', 'class_enrollments', type_='unique')
    op.alter_column('course_files', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('course_files', 'file_type',
               existing_type=postgresql.ENUM('pdf', 'video', 'image', 'document', 'audio', 'other', name='file_type'),
               nullable=True)
    op.alter_column('courses', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('document_chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_chunks_class', table_name='document_chunks')
    op.drop_index('idx_chunks_course', table_name='document_chunks')
    op.drop_index('idx_chunks_embedding', table_name='document_chunks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('evaluations', 'type',
               existing_type=postgresql.ENUM('quiz', 'devoir', 'examen', 'controle', 'oral', 'projet', name='evaluation_type'),
               nullable=True)
    op.alter_column('evaluations', 'max_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('20.0'))
    op.alter_column('evaluations', 'coefficient',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('grades', 'evaluation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('grades', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('grades', 'score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('grades_evaluation_id_student_id_key', 'grades', type_='unique')
    op.drop_index('idx_grades_evaluation', table_name='grades')
    op.drop_index('idx_grades_student', table_name='grades')
    op.alter_column('messages', 'thread_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_messages_thread', table_name='messages')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('absence', 'grade_published', 'message', 'ai_response', 'quiz_available', 'event', 'system', 'decrochage_alert', name='notification_type'),
               nullable=True)
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.alter_column('quiz_attempts', 'quiz_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('quiz_attempts', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('quiz_attempts', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('quiz_attempts', 'score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('quiz_attempts', 'max_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('idx_quiz_attempts_student', table_name='quiz_attempts')
    op.alter_column('quiz_questions', 'quiz_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('quiz_questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('student_badges', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('student_badges', 'badge_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('student_badges_student_id_badge_id_key', 'student_badges', type_='unique')
    op.alter_column('student_parent_links', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('student_parent_links', 'parent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('student_parent_links_student_id_parent_id_key', 'student_parent_links', type_='unique')
    op.alter_column('student_profiles', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('student_profiles', 'adaptive_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.500'))
    op.alter_column('student_profiles', 'avatar_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('subjects', 'coefficient',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('teacher_subject_assignments', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('teacher_subject_assignments', 'subject_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('teacher_subject_assignments', 'class_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('teacher_subject_assignments_teacher_id_subject_id_class_id__key', 'teacher_subject_assignments', type_='unique')
    op.alter_column('thread_participants', 'thread_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('thread_participants', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('thread_participants_thread_id_user_id_key', 'thread_participants', type_='unique')
    op.alter_column('timetable_slots', 'class_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('timetable_slots', 'day',
               existing_type=postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='schedule_day'),
               nullable=True)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('xp_transactions', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('xp_transactions', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('timetable_slots', 'day',
               existing_type=postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='schedule_day'),
               nullable=False)
    op.alter_column('timetable_slots', 'class_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('thread_participants_thread_id_user_id_key', 'thread_participants', ['thread_id', 'user_id'])
    op.alter_column('thread_participants', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('thread_participants', 'thread_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('teacher_subject_assignments_teacher_id_subject_id_class_id__key', 'teacher_subject_assignments', ['teacher_id', 'subject_id', 'class_id', 'academic_year_id'])
    op.alter_column('teacher_subject_assignments', 'class_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('teacher_subject_assignments', 'subject_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('teacher_subject_assignments', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('subjects', 'coefficient',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('student_profiles', 'avatar_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('student_profiles', 'adaptive_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text('0.500'))
    op.alter_column('student_profiles', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('student_parent_links_student_id_parent_id_key', 'student_parent_links', ['student_id', 'parent_id'])
    op.alter_column('student_parent_links', 'parent_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('student_parent_links', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('student_badges_student_id_badge_id_key', 'student_badges', ['student_id', 'badge_id'])
    op.alter_column('student_badges', 'badge_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('student_badges', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('quiz_questions', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('quiz_questions', 'quiz_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_quiz_attempts_student', 'quiz_attempts', ['student_id'], unique=False)
    op.alter_column('quiz_attempts', 'max_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('quiz_attempts', 'score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('quiz_attempts', 'answers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('quiz_attempts', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('quiz_attempts', 'quiz_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id', 'is_read'], unique=False)
    op.alter_column('notifications', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('absence', 'grade_published', 'message', 'ai_response', 'quiz_available', 'event', 'system', 'decrochage_alert', name='notification_type'),
               nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_messages_thread', 'messages', ['thread_id', 'created_at'], unique=False)
    op.alter_column('messages', 'thread_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_grades_student', 'grades', ['student_id'], unique=False)
    op.create_index('idx_grades_evaluation', 'grades', ['evaluation_id'], unique=False)
    op.create_unique_constraint('grades_evaluation_id_student_id_key', 'grades', ['evaluation_id', 'student_id'])
    op.alter_column('grades', 'score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('grades', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('grades', 'evaluation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('evaluations', 'coefficient',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('evaluations', 'max_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('20.0'))
    op.alter_column('evaluations', 'type',
               existing_type=postgresql.ENUM('quiz', 'devoir', 'examen', 'controle', 'oral', 'projet', name='evaluation_type'),
               nullable=False)
    op.create_index('idx_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_chunks_course', 'document_chunks', ['course_id'], unique=False)
    op.create_index('idx_chunks_class', 'document_chunks', ['class_id'], unique=False)
    op.alter_column('document_chunks', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('courses', 'tags',
               existing_type=sa.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('course_files', 'file_type',
               existing_type=postgresql.ENUM('pdf', 'video', 'image', 'document', 'audio', 'other', name='file_type'),
               nullable=False)
    op.alter_column('course_files', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('class_enrollments_student_id_class_id_academic_year_id_key', 'class_enrollments', ['student_id', 'class_id', 'academic_year_id'])
    op.alter_column('class_enrollments', 'class_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('class_enrollments', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audit_logs', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_announcements_slug'), table_name='announcements')
    op.create_index('idx_ann_status_visibility', 'announcements', ['status', 'visibility'], unique=False)
    op.create_index('idx_ann_slug', 'announcements', ['slug'], unique=False)
    op.create_index('idx_ann_publish_at', 'announcements', ['publish_at'], unique=False)
    op.create_index('idx_ann_pinned', 'announcements', ['pinned', sa.text('priority DESC')], unique=False)
    op.create_unique_constraint('announcements_slug_key', 'announcements', ['slug'])
    op.alter_column('announcements', 'priority',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint('uq_announcement_user_emoji', 'announcement_reactions', ['announcement_id', 'user_id', 'emoji'])
    op.create_index('idx_ai_messages_conversation', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    op.alter_column('ai_messages', 'feedback',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('ai_messages', 'confidence_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('ai_messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', 'system', name='message_role'),
               nullable=False)
    op.alter_column('ai_messages', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ai_conversations', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_absences_student', 'absences', ['student_id'], unique=False)
    op.create_index('idx_absences_date', 'absences', ['date'], unique=False)
    # ### end Alembic commands ###
