"""revert grades to NUMERIC for exact decimal precision

Revision ID: fe1460476a39
Revises: 44c6e4431407
Create Date: 2026-06-06 23:11:47.615417

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "fe1460476a39"
down_revision: str | None = "44c6e4431407"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evaluations",
        "max_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
        existing_server_default=sa.text("20.0"),
    )
    op.alter_column(
        "evaluations",
        "coefficient",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=3, scale=1),
        existing_nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    op.alter_column(
        "grades",
        "score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "quiz_attempts",
        "score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "quiz_attempts",
        "max_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "subjects",
        "coefficient",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=3, scale=1),
        existing_nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subjects",
        "coefficient",
        existing_type=sa.Numeric(precision=3, scale=1),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    op.alter_column(
        "quiz_attempts",
        "max_score",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "quiz_attempts",
        "score",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "grades",
        "score",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "evaluations",
        "coefficient",
        existing_type=sa.Numeric(precision=3, scale=1),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    op.alter_column(
        "evaluations",
        "max_score",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        existing_server_default=sa.text("20.0"),
    )
    # ### end Alembic commands ###
